### ISSUE TITLE
[Feature]: Deal with missing values (if any)

### ISSUE THREAD

**Issue by TheMimikyu** [OPCODE-Open-Spring-Fest/hidden-consumer-patterns#1]
### So, what is it about?

Check for missing values in the dataset and fill the missing values using appropriate method. Provide justification for the method taken.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by anshumsj** [comment]
i want to solve this

**Comment by anshumsj** [comment]
sir dataset kaha hai ?

**Comment by TheMimikyu** [comment]
> sir dataset kaha hai ?

It's in the `dataset` folder. 
You may also, go through the `Project_Tour.md` for better understanding.

**Comment by ritikgupta65** [comment]
Please assign this issue to me. @TheMimikyu

**Comment by TheMimikyu** [comment]
> Please assign this issue to me. @TheMimikyu

This Issue has been assigned to you. @ritikgupta65 
You have `2 days` to solve the issue.

**Comment by TheMimikyu** [comment]
This issue has been resolved by PR #8.
