### ISSUE TITLE
[Feature]: Data Cleaning: Remove Non-Discriminatory Features

### ISSUE THREAD

**Issue by TheMimikyu** [OPCODE-Open-Spring-Fest/hidden-consumer-patterns#10]
### So, what is it about?

You have to `clean the data` by removing features that do not contribute to the model’s predictive power by identifying `Single-Valued Functon.`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ritikgupta65** [comment]
kindly  assign this issue  to me @TheMimikyu

**Comment by TheMimikyu** [comment]
Issue has been resolved in #15 by @ritikgupta65 .
