### ISSUE TITLE
[Feature]: Univariate Plots, Outlier Detection and Removal in Engineered Features

### ISSUE THREAD

**Issue by TheMimikyu** [OPCODE-Open-Spring-Fest/hidden-consumer-patterns#3]
### So, what is it about?

This issue focuses on the need for visualizing the engineered features and `AnnualIncome` using univariate plots. The task involves the following steps:

1. **Univariate Plots**: Generate univariate plots for the engineered features to understand their individual characteristics.

2. **Outlier Detection**: Implement outlier detection using boxplots. This will help identify any extreme values that may adversely affect our analysis.

3. **Dealing with Outliers**: Once outliers are detected, devise a strategy to handle them. This could involve removing these outliers or adjusting them to fall within an acceptable range.

4. **Final Plot without Outliers**: After dealing with the outliers, generate the final univariate plots without the outliers. This will give us a more accurate representation of the engineered features.

This issue is crucial for ensuring the quality and reliability of our data analysis. Any progress or updates regarding this issue will be posted here.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ritikgupta65** [comment]
please assign this issue to me @TheMimikyu

**Comment by TheMimikyu** [comment]
> please assign this issue to me @TheMimikyu

You've been assigned this issue for 4 working days.

**Comment by TheMimikyu** [comment]
Issue has been resolved in #13.
