### ISSUE TITLE
[Feature]: AnnualIncome Analysis by AcademicLevel and Statistical Testing

### ISSUE THREAD

**Issue by TheMimikyu** [OPCODE-Open-Spring-Fest/hidden-consumer-patterns#4]
### So, what is it about?

This issue focuses on the need for a detailed analysis of `AnnualIncome` by `AcademicLevel`. The task involves the following steps:

1. **AnnualIncome by AcademicLevel Plot**: Generate a plot to visualize the distribution of `AnnualIncome` across different `AcademicLevel`s. This will help us understand if there are significant differences in income levels across different academic qualifications.

2. **Statistical Test**: Perform a statistical test to check if the average `AnnualIncome` is the same for PHD owners and Master degree owners. 

3. **Null and Alternate Hypothesis Statements**: Clearly state the null and alternate hypotheses for the statistical test. The null hypothesis could be that the average `AnnualIncome` is the same for both PHD and Master degree owners, while the alternate hypothesis could be that the average `AnnualIncome` is not the same for these two groups.

4. **Significance Level and Test Method**: Specify the significance level chosen for the test (for example, 0.05) and detail the test method used.

This issue is crucial for understanding the impact of academic qualifications on income levels. Any progress or updates regarding this issue will be posted here.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaKumar5155** [comment]
Assign this issue to me

**Comment by TheMimikyu** [comment]
> Assign this issue to me

@AdityaKumar5155 You've been assigned this issue for 2 Days.

**Comment by TheMimikyu** [comment]
Issue has been solved by @AdityaKumar5155 with PR #6.
